site_name: Rakugo Core Docs
repo_url: https://github.com/rakugoteam/Rakugo

extra:
  homepage: https://rakugoteam.github.io
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/
      lang: en

theme:
  name: material
  logo: logo.svg
  palette:
    scheme: slate
    primary: deep purple
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
